### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by arpunk**
This upgrades the library to be used with rebar3.

The riakc dependency is specified directly from github because of [dependency issues](https://github.com/basho/riak-erlang-client/issues/341#issuecomment-269675132), however it tracks latest stable release.

### CODE REVIEW

**Comment by oubiwann** [comment]
Looks like we need to tweak the travis config file, too.

**Comment by arpunk** [comment]
Tests are not passing currently (same with kanin). Maybe we need to fix those and then fix travis to build using rebar3.

**Comment by oubiwann** [comment]
I've got a fix in place for lric ... should be good on the next Travis run ...

**Comment by oubiwann** [comment]
Phew! Well, that took more juggling than expected. Tests passing now, though.

**Pull request merged**
